source:       .
destination:  ./build-site/
layouts_dir: ./themes/jekyll/_layouts/
includes_dir: ./themes/jekyll/_includes/

# This adds github pages data
gems: ['jekyll-github-metadata']

# See http://jekyllrb.com/docs/collections/
collections:
  examples:
    output: true
