source:       .
destination:  ./build-site/
layouts_dir: ./themes/jekyll/_layouts/
includes_dir: ./themes/jekyll/_includes/

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# This adds github pages data
gems: ['jekyll-github-metadata']

# See http://jekyllrb.com/docs/collections/
collections:
  examples:
    output: true
  how_tos:
    output: true
